server:
  port: 9000

spring:
  application:
    name: oauth-authorization-server
  datasource:
    url: jdbc:mysql://localhost:3306/userregistration?useSSL=false&serverTimezone=UTC
    username: scalerstudent
    password: scalerstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

oauth2:
  client:
    id: 1UAgiN6lFlofeKektGe8shev
    secret: gFXMW7o3glw3pJtk2FjbxfCpqgnEttcsQl_83pW8fTc_cO4E

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG